import { FC, memo } from 'react';
import { AxiosResponse } from 'axios';
import Posts from 'components/Posts/Posts';
import { fetchCategories, fetchPosts } from '../http';
import { GetServerSideProps } from 'next';
import Head from 'next/head';
import Tabs from 'components/Tabs/Tabs';

interface IPropTypes {
  dataPost: IArticle[];

  categories: {
    items: ICategory[];
  };
}

const Blog: FC<IPropTypes> = ({ dataPost, categories }) => {
  return (
    <>
      <Head>
        <title>SL PORTFOLIO - БЛОГ </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Tabs categories={categories.items} />
        <Posts posts={dataPost} />
      </main>
    </>
  );
};

export default Blog;

export const getServerSideProps: GetServerSideProps = async () => {
  const { data }: AxiosResponse<ICollectionResponse<IArticle[]>> = await fetchPosts(
    'populate=*'
  );

  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();

  return {
    props: {
      categories: {
        items: categories.data,
      },
      dataPost: data.data,
    },
  };
};
