import AboutSection from 'components/AboutSection/AboutSection';
import ContactSection from 'components/ContactSection/ContactSection';
import HeroSection from 'components/HeroSection/HeroSection';
import Head from 'next/head';

const Home = () => {
  return (
    <>
      <Head>
        <title>SL PORTFOLIO - Портфолио Арсенюк Данил </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeroSection />
      <AboutSection />
      <ContactSection />
    </>
  );
};

export default Home;
