import { AxiosResponse } from 'axios';
import TabsFilter from 'components/TabsFilter/TabsFilter';
import { fetchCategoriesPortfolio, fetchPortfolio } from '../http';
import { GetServerSideProps } from 'next';
import { FC } from 'react';
import PortfolioCard from 'components/PortfolioCard/PortfolioCard';
import Head from 'next/head';

interface IPropTypes {
  dataPost: IArticle[];

  categories: {
    items: ICategory[];
  };
}

const portfolios: FC<IPropTypes> = ({ categories, dataPost }) => {
  return (
    <>
      <Head>
        <title>SL PORTFOLIO - Проекты</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <TabsFilter categories={categories.items} />
        {dataPost &&
          dataPost.map((post) => {
            return <PortfolioCard key={post.id} post={post.attributes} />;
          })}
      </div>
    </>
  );
};

export default portfolios;

export const getServerSideProps: GetServerSideProps = async () => {
  const { data }: AxiosResponse<ICollectionResponse<IArticle[]>> = await fetchPortfolio(
    'populate=*'
  );

  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategoriesPortfolio();

  return {
    props: {
      categories: {
        items: categories.data,
      },
      dataPost: data.data,
    },
  };
};
